### ISSUE TITLE
colorizeSdf2d Has errors

### ISSUE THREAD

**Issue by grinchdubs** [t3kt/raytk#1136]
Im trying to follow the RayTK Scene: Warped Hexagons Tutorial and the colorizeSdf2d material operator has shader errors. The preview looks as it does in your video however the op doesnt output anything. 

Tried on both 2022.33910 and 2022.35280 both running RayTK 0.36 and RayTK 0.33, however it does work in 2022.31030. It Must be some glsl change in TD

**Comment by t3kt** [comment]
Can you see what the errors are?
Either with the inspector or going into the render2d and looking for the info dat linked to the glsl top?

**Comment by grinchdubs** [comment]
When I open up the inspector, It shows that the shader has errors at the top but the shader compile info says successfully compiled

![Screenshot 2023-10-11 190046](https://github.com/t3kt/raytk/assets/26509343/1ba0a73f-8efa-4414-ac16-319973a71a63)

**Comment by t3kt** [comment]
Can you provide a screenshot of the network inside render2D, specifically the group of operators to the right of the vertical line of TOPs, with the middle mouse held down on the glsl TOP?

Example:
![image](https://github.com/t3kt/raytk/assets/894413/d1a6badf-db70-4f23-98f3-99bef8ff2d71)

**Comment by grinchdubs** [comment]
Here you go
![Screenshot 2023-10-11 192430](https://github.com/t3kt/raytk/assets/26509343/935efe05-3d10-4862-a92b-9cc62f684b53)


So for shits and giggles I changed my 2D render resolution to 1280x720 and that gave me an output

![Screenshot 2023-10-11 192616](https://github.com/t3kt/raytk/assets/26509343/e078f8fa-61bc-42d3-8267-4a4146776e19)

**Comment by t3kt** [comment]
aaahh. ok. that makes sense. It should be possible to check for that error and show it more clearly from outside the renderer comp
