### ISSUE TITLE
'CallbacksExt' object has no attribute 'OptimalHeight'

### ISSUE THREAD

**Issue by ajmirsky** [t3kt/raytk#1137]
TD Version: 2023.10130 (experimental)
Mac M1, Ventura 13.5.2

As this is in the experimental version, it may/may not be an issue in the final release of TD 2023, but wanted to make someone aware as I can't tell if this is a bug in TD 2023 or in RayTK.

`raytk > tools > inspector > bufferInspector > normalization_dropmenu`

and

`raytk > tools > inspector > shaderPanel > codeBlock_dropmenu`

![image](https://github.com/t3kt/raytk/assets/323371/2333cf8f-43fd-4fcd-8ac8-1542a2088836)

**Comment by t3kt** [comment]
This is a compatibility issue with old widgets in the new TD experimental. See #1120.
The fix will be included in the 0.37 release.
