### ISSUE TITLE
Problem with World Position output from RaymarchRender ROP

### ISSUE THREAD

**Issue by WMAcademy** [t3kt/raytk#1207]
Hi!
While I was following your tutorial series (part 8: depth and buffers) I found some problems with the world position output. It gives me an empty output and the ROPs don't give me any error. The switch for that output is enable and I cannot solve the problem.

There are the information requested:
- RayTK version: 0.39
- Information from the inspector:
    - Validation errors/warnings: none
    - Shader compile errors/warnings: none
- OS: windows 11
- GPU: NVIdia RTX 3060
- GPU driver version: 31.0.15.4612

Thanks in advance

**Comment by t3kt** [comment]
Do you have a file with an example?
I attempted to reproduce the issue but it seems to be working properly for me.

I tried using worldPosMap:

![image](https://github.com/t3kt/raytk/assets/894413/5bb9a8c5-e355-4149-8f1d-3949b3c211f9)

And also renderSelect:

![image](https://github.com/t3kt/raytk/assets/894413/40e63da9-c9cd-47e8-8486-cb2120581fbb)

**Comment by WMAcademy** [comment]
I just found out that by referencing the RaymarchRender OP inside the WorldsMap OP as you did just works fine! Before that i've connected the two operators directly and it gave me no results but I can resolve with tha method,
Thanks!

**Comment by t3kt** [comment]
Got it. That input is designed to take in the worldPos output from a raymarchRender3D, so if you connect the main color output from the renderer it isn't going to do what you want.

**Comment by t3kt** [comment]
I'm updating the input label and the docs to clarify.
