### ISSUE TITLE
Collapse all categories

### ISSUE THREAD

**Issue by M1tji** [t3kt/raytk#1253]
When using RayTK, the first thing I do is opening the Palette modal, pinning it and close all categories one by one. I find it easier for me to browse the palette that way, but I'm getting tired of closing all the categories each time I open a project.

So this is an enhancement request :
Allowing the user to collapse/open all categories 
It could be done with a button at the bottom of the modal

Thanks !

**Comment by t3kt** [comment]
Fortunately this is already supported!
<img width="300" alt="image" src="https://github.com/user-attachments/assets/2e598b1e-c138-47a3-8af4-c1ce8afa125b">
Though looks like the tooltips are wrong so I'll fix those.
