### ISSUE TITLE
Warning for addon version mismatch

### ISSUE THREAD

**Issue by t3kt** [t3kt/raytk#1269]

**Comment by shuyang979** [comment]
Hello, I also have this situation. How do I solve the problem of editing in different versions?

**Comment by t3kt** [comment]
RayTK operators are can only be connected to other operators from the same version. Each operator has an "Update OP" parameter which when pulsed will update it to whatever version of the main toolkit comp is loaded. So as long as you have the toollkit, and the addon packages all with the same version, you should be able to do that update process on all of the operators and they'll all update to the same version and work together.

**Comment by shuyang979** [comment]
Thank you so much!!! Clicking on "Update OP" worked!
