### ISSUE TITLE
Unable to update /sys/ quiet/base 12/ fieldCamera1, no clone master found

### ISSUE THREAD

**Issue by doughboy47** [t3kt/raytk#1273]
I used this video as a tutorial (https://www.youtube.com/watch?v=0H34yEHkMNw&t=37s) and followed the instructions. Yet when I drop the tox file, it is still working, but when I drop operators from the toolkits, a "warning" pops up, and the result is a checkboard with red and blue.

My issue report:

- Raytk version 0.43
- Shader has errors!
- Vertex Shader Compile Results:

Compiled Successfully

=============
Pixel Shader Compile Results:
ERROR: /project1/raymarchRender3D/shaderExecutor/shader_code:445: '=' :  cannot convert from ' global highp vec4' to ' temp { global highp float x,  global highp vec3 mat,  global bool useShadow}'
ERROR: 1 compilation errors.  No code generated.

Computer:

OS: Windows 11
GPU: Geforce RTX 3050 Ti Laptop GPU
GPU Driver Version: 560.81
![Uploading Screenshot (1643).png…]()

**Comment by t3kt** [comment]
See [1270](https://github.com/t3kt/raytk/issues/1270) for a workaround

**Comment by t3kt** [comment]
Looks like there's also a secondary issue here where a vector field is plugged into something that's expecting an SDF, unrelated to the cloning issue.
