### ISSUE TITLE
inspector crashes TD

### ISSUE THREAD

**Issue by delray** [t3kt/raytk#323]
Hi, I hope this is the right place to report this issue...let me know if not.  Basically everytime I try and use the inspector, it crashes TD completely. Even if the network is just a single ROP box sdf. 
System details are: 
TD 2021.10330 commercial
Windows 10 v 20H2 build 19042.804
Nvidia 3090 461.40 studio drivers

let me know if i can help to track the issue down.  love the software btw, I know a little raymarching already, but its nice to have a sandbox to play in quickly and easily!

**Comment by t3kt** [comment]
Yes, this is the right place to report the issue.

Do you get a crash dump file and a "CrashAutoSave.foo.toe" file? I can't examine the crash dump file but Derivative could probably provide some info if you sent it to them. That might at least give us some more info to work with.

What happens if you navigate into `raytk/tools/inspector` without using "Inspect"? If that doesn't crash it, you could try disabling cooking on portions of the components in there and then using "Inspect".

**Comment by delray** [comment]
There's no crash file unfortunately, but i did disconnect my second monitor and it works OK. Even with the simplest network, just a box sdf, it would crash with the second monitor connected. clicking inspector opens a window that is spanning the two monitors, so maybe there is something there. For the record, my main monitor is 2560 x 1440 and the second is just one i use to output and is only 1920 x 1080 so that might further complicate things. 

navigating to `raytk/tools/inspector 'view'` worked fine btw, but it only opened on the main monitor, it didnt try and span.
I'm happy to test anything else out as well on my side if i can help...

**Comment by delray** [comment]
OK. clicking the custom parameter @ `raytk/tools/inspector` crashed it as well as it tried to span the monitors. I went inside the inspector container, and on the 'window' node, I simply changed the parameter to force it to open on the primary monitor and it all works fine now.  

I think it had to do with the fact that my secondary monitor was smaller and possibly that it was also to the left created some issues.  forcing it to the primary seems to have solved it!

**Comment by t3kt** [comment]
Interesting. Does it also do that if you create a window comp in an empty project and set it to go to the second monitor and open it?
I'm trying to figure out the best balance for monitor placement for that tool. It's kind of hard to use if it's on top of the network, so I had it default to another monitor, but that doesn't always work either.
This seems like a TD-level bug though, especially if you can reproduce it in another project.

**Comment by delray** [comment]
Yep! sure does! Ill file a bug report on the forum, sorry to bother you here, but thanks for helping to chase it down...
