### ISSUE TITLE
Parameter pages hidden from component properties

### ISSUE THREAD

**Issue by catronomix** [t3kt/raytk#487]
No matter which version of RayTK I try with, I'm getting this weird result where the parameter pages menu is gone from any raytk component I add to the network. See screenshot, using TD 2021.12380:
![image](https://user-images.githubusercontent.com/42138122/117286509-933d4f80-ae69-11eb-9cac-d8428e99d251.png)

**Comment by catronomix** [comment]
If I run op('raymarchRender3D').showCustomOnly = False, the pages re-appear. Possibly a bug on TD's side with the latest update

**Comment by t3kt** [comment]
Thanks for the report!
Yes, this is a TD bug: https://forum.derivative.ca/t/showcustomonly-page-header-disappears-td-2021-12380/181948/2
The other workaround is to use a Parameter COMP.

**Comment by t3kt** [comment]
showCustomOnly is set during the build process on the operator masters that the palette clones.

I guess if you wanted to change that you could do something like this:

```python
for o in ops('<insert path to toolkit>/operators/*/*'):
   if o.isCOMP:
      o.showCustomOnly = False
```

alternatively you could stick this in a DAT and run it after adding a renderer:
```python
for o in ops('raymarchRender*'):
  o.showCustomOnly = True
```

There are very few operators that have more than a single page. It's mostly just the renderers. Hopefully Derivative will fix that bug. Feel free to comment on the forum thread to give it some extra weight.

Are you trying to change the built-in parameters for some reason, or is it just as a workaround for the TD bug?

**Comment by catronomix** [comment]
Seems solved with raytk0.14 and td 2021.13610
