### ISSUE TITLE
Include directive support detection failing for AMD Radeon pro 575

### ISSUE THREAD

**Issue by antithug** [t3kt/raytk#589]
I'm new to TD, and I'm having trouble getting the simplest things working with raytk.

I've tried loading multiple toe files from the tutorials on YouTube, and they all seem to be running, but the output is always a grid of red/blue boxes. 

If I simplify the networks to the just a boxsdf -> renderer -> out, it's the same thing. Everything is running with no errors, but the output is just the grid of red/blue boxes. 

I'm sure I'm doing something stupid, but I don't know how to proceed.

**Comment by t3kt** [comment]
It might be a driver compatibility issue, especially if it always happens for all RayTK networks.
A few things to check:
* Are there any errors/warnings showing on any of the ops in the network? If so, middle click on them to see what error message is shown.
* On the renderer, click the "Inspect" parameter. Switch to the "shader" tab. Down at the bottom you'll see some sort of error message.

Also:
* OS
* GPU
* TD version
* Toolkit version

In some early versions there were issues that caused compiler failures on certain AMD cards.

Might want to try updating your GPU drivers.

**Comment by antithug** [comment]
FYI, I'm using a 2017 iMac running windows with a radeon pro 575. I updated the drivers (dated Oct. 2020), but still got the same result. Old card, but the driver update didn't help.

**Comment by antithug** [comment]
I see, there are errors. Here they are:

Pixel Shader Compile Results: 
Fragment shader failed to compile with the following errors:
ERROR: 0:95: error(#110) Invalid Directive: include
ERROR: 0:96: error(#110) Invalid Directive: include
ERROR: 0:97: error(#110) Invalid Directive: include
ERROR: 0:98: error(#110) Invalid Directive: include
ERROR: 0:102: error(#132) Syntax error: "Sdf" parse error
ERROR: error(#273) 5 compilation errors.  No code generated

**Comment by antithug** [comment]
Is there any way I can edit this in TD to inline the includes?

**Comment by antithug** [comment]
I'm perusing the code, and it looks like there is a way to pass something to the Shader Builder Config? Will that work.

I'm new to TD, so not quite sure how to do it.

**Comment by antithug** [comment]
I got it working in a roundabout way. I'm sure it's not the right way. I drilled into the 'shaderBuilder' node and changed the code to just default to 'inlineall'

mode = str(self.configPar()['Includemode'] or 'inlineall')

This worked and I'm getting output. I'm sure there is a way to pass this 'inlineall' through the shaderBuilderConfig, but I don't know the correct syntax.

**Comment by t3kt** [comment]
There's a component called `supportDetector` inside `shaderBuilder` that is supposed to identify when a GPU driver doesn't support includes. When that happens it overrides the config `Includemode` setting. Take a look inside `supportDetector` and see if the GLSL TOP in there is showing any errors or warnings.

**Comment by t3kt** [comment]
See also #34

**Comment by m0netize** [comment]
![tekt](https://user-images.githubusercontent.com/59104752/127945663-8cfb2db3-6e89-40d7-a867-40503235e349.PNG)

Here is a photo of the error in supportDetector. If I change the table to include 0, it works.

**Comment by t3kt** [comment]
Interesting. It should be treating anything sort of OP warning on the TOP as an indication that includes aren't supported. It checks when the op is created, and on startup, and updates the table.

Originally it used a script DAT that would rebuild the table if anything about the TOP changed, but there was something causing the TOP to change on every frame, which caused the shader to rebuild constantly.

Either the detection is somehow failing to notice the warning, or at the time when the detection runs, there isn't yet a warning.

You could try adding this to `buildSupportTable()`:

```python
def buildSupportTable(
		support: 'scriptDAT',
		top: 'glslTOP'):
	top.cook(force=True)  # <--- new part
	support.clear()
	support.appendRow([
		'include',
		int(_supportsInclude(top)),
	])
```

Then with that change saved in there, reload the project.
It's possible that the TOP isn't cooking for some reason which prevents the warning from showing up.

In the 0.16 release there will be an easier way to customize the shader settings which would let you force it to use inlining. Not sure when that version will be out though.
