### ISSUE TITLE
colorRampField parameter

### ISSUE THREAD

**Issue by grinchdubs** [t3kt/raytk#844]
Is it possible to add some more parameters to the colorRampField like Type, Phase or Period in addition to some kind of amplitude control

**Comment by t3kt** [comment]
That can be done by connecting a waveField to the Coordinate Field input on colorRampField.
colorRampField is basically a way to map a single value to a range of colors. By default it uses one of the coordinate axes for that value, but it can use whatever other source of values using that input.

**Comment by grinchdubs** [comment]
That did it thank you!
