### ISSUE TITLE
Helpcommand Path causing redX

### ISSUE THREAD

**Issue by grinchdubs** [t3kt/raytk#912]
The Docshelper container is having issues with the current path cauing a redX
![image](https://user-images.githubusercontent.com/26509343/177061347-a37c7bcb-049f-4e05-9385-ab1d6890790b.png)

**Comment by t3kt** [comment]
Where in RayTK is this showing up?

**Comment by grinchdubs** [comment]
I was just realizing I forgot to mention this. RayTK 0.24 with Latest version of TD (2022.25370)

**Comment by grinchdubs** [comment]
Locations are Below, there are 2
![image](https://user-images.githubusercontent.com/26509343/177063568-2e429756-3013-4e6d-a528-025ff35d3915.png)
![image](https://user-images.githubusercontent.com/26509343/177063615-9f320182-13cf-46d5-a7d9-be06588df119.png)
